//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.21 at 12:07:23 PM CEST 
//

package org.xmlws.userservice.model;

import java.math.BigDecimal;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.hibernate.boot.jaxb.hbm.spi.Adapter5;
import org.hibernate.boot.jaxb.hbm.spi.Adapter6;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="price" type="{https://github.com/mare11/XML_MegaTravel/accommodation}TPrice"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "startDate", "endDate", "price" })
@XmlRootElement(name = "PeriodPrice")
@Entity
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class PeriodPrice {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@XmlElement(required = true, type = String.class)
	@XmlJavaTypeAdapter(Adapter5.class)
	@XmlSchemaType(name = "date")
	@Column(name = "start_date", nullable = false)
	protected LocalDate startDate;

	@XmlElement(required = true, type = String.class)
	@XmlJavaTypeAdapter(Adapter6.class)
	@XmlSchemaType(name = "date")
	@Column(name = "end_date", nullable = false)
	protected LocalDate endDate;

	@XmlElement(required = true)
	@Column(name = "price", nullable = false)
	protected BigDecimal price;

	@XmlElement(name = "Accommodation", required = true)
	@ManyToOne(fetch = FetchType.EAGER)
	protected Accommodation accommodation;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the value of the startDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public LocalDate getStartDate() {
		return startDate;
	}

	/**
	 * Sets the value of the startDate property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStartDate(LocalDate value) {
		this.startDate = value;
	}

	/**
	 * Gets the value of the endDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public LocalDate getEndDate() {
		return endDate;
	}

	/**
	 * Sets the value of the endDate property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEndDate(LocalDate value) {
		this.endDate = value;
	}

	/**
	 * Gets the value of the price property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * Sets the value of the price property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setPrice(BigDecimal value) {
		this.price = value;
	}

	/**
	 * Gets the value of the accommodation property.
	 * 
	 * @return possible object is {@link Accommodation }
	 * 
	 */
	public Accommodation getAccommodation() {
		return accommodation;
	}

	/**
	 * Sets the value of the accommodation property.
	 * 
	 * @param value allowed object is {@link Accommodation }
	 * 
	 */
	public void setAccommodation(Accommodation value) {
		this.accommodation = value;
	}

}
