//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 01:36:05 PM CEST 
//


package https.github_com.mare11.xml_megatravel.reservation;

import java.time.LocalDateTime;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter9
    extends XmlAdapter<String, LocalDateTime>
{


    public LocalDateTime unmarshal(String value) {
        return (org.xmlws.util.TypeConverter.parseDateTime(value));
    }

    public String marshal(LocalDateTime value) {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

}
