//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.21 at 12:07:23 PM CEST 
//

package org.xmlws.userservice.model;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.hibernate.boot.jaxb.hbm.spi.Adapter1;
import org.hibernate.boot.jaxb.hbm.spi.Adapter2;
import org.hibernate.boot.jaxb.hbm.spi.Adapter3;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://github.com/mare11/XML_MegaTravel/accommodation}Accommodation"/>
 *         &lt;element ref="{https://github.com/mare11/XML_MegaTravel/user}User"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="realized" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{https://github.com/mare11/XML_MegaTravel/reservation}ReservationRating"/>
 *         &lt;element ref="{https://github.com/mare11/XML_MegaTravel/reservation}Message" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "accommodation", "user", "startDate", "endDate", "realized", "reservationRating",
		"message" })
@XmlRootElement(name = "Reservation")
@Entity
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Reservation {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@XmlElement(name = "Accommodation", namespace = "https://github.com/mare11/XML_MegaTravel/accommodation", required = true)
	@ManyToOne(fetch = FetchType.EAGER)
	protected Accommodation accommodation;

	@XmlElement(name = "User", namespace = "https://github.com/mare11/XML_MegaTravel/user", required = true)
	@ManyToOne(fetch = FetchType.EAGER)
	protected User user;

	@XmlElement(required = true, type = String.class)
	@XmlJavaTypeAdapter(Adapter1.class)
	@XmlSchemaType(name = "date")
	@Column(name = "start_date", nullable = false)
	protected LocalDate startDate;

	@XmlElement(required = true, type = String.class)
	@XmlJavaTypeAdapter(Adapter2.class)
	@XmlSchemaType(name = "date")
	@Column(name = "end_date", nullable = false)
	protected LocalDate endDate;

	@XmlElement(required = true, type = String.class)
	@XmlJavaTypeAdapter(Adapter3.class)
	@XmlSchemaType(name = "boolean")
	@Column(name = "realized", nullable = false)
	protected Boolean realized;

	@XmlElement(name = "ReservationRating", required = true)
	@OneToOne(fetch = FetchType.EAGER)
	protected ReservationRating reservationRating;

	@XmlElement(name = "Message")
	@OneToMany(mappedBy = "reservation", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	protected Set<Message> messages = new HashSet<>();

	@Version
	private Long version;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the value of the accommodation property.
	 * 
	 * @return possible object is {@link Accommodation }
	 * 
	 */
	public Accommodation getAccommodation() {
		return accommodation;
	}

	/**
	 * Sets the value of the accommodation property.
	 * 
	 * @param value allowed object is {@link Accommodation }
	 * 
	 */
	public void setAccommodation(Accommodation value) {
		this.accommodation = value;
	}

	/**
	 * Gets the value of the user property.
	 * 
	 * @return possible object is {@link User }
	 * 
	 */
	public User getUser() {
		return user;
	}

	/**
	 * Sets the value of the user property.
	 * 
	 * @param value allowed object is {@link User }
	 * 
	 */
	public void setUser(User value) {
		this.user = value;
	}

	/**
	 * Gets the value of the startDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public LocalDate getStartDate() {
		return startDate;
	}

	/**
	 * Sets the value of the startDate property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStartDate(LocalDate value) {
		this.startDate = value;
	}

	/**
	 * Gets the value of the endDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public LocalDate getEndDate() {
		return endDate;
	}

	/**
	 * Sets the value of the endDate property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEndDate(LocalDate value) {
		this.endDate = value;
	}

	/**
	 * Gets the value of the realized property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Boolean isRealized() {
		return realized;
	}

	/**
	 * Sets the value of the realized property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setRealized(Boolean value) {
		this.realized = value;
	}

	/**
	 * Gets the value of the reservationRating property.
	 * 
	 * @return possible object is {@link ReservationRating }
	 * 
	 */
	public ReservationRating getReservationRating() {
		return reservationRating;
	}

	/**
	 * Sets the value of the reservationRating property.
	 * 
	 * @param value allowed object is {@link ReservationRating }
	 * 
	 */
	public void setReservationRating(ReservationRating value) {
		this.reservationRating = value;
	}

	/**
	 * Gets the value of the message property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the message property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMessage().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Message }
	 * 
	 * 
	 */
	public List<Message> getMessage() {
		if (messages == null) {
			messages = new HashSet<Message>();
		}
		return new ArrayList<>(this.messages);
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

}
