//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.29 at 07:30:27 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/mare11/XML_MegaTravel/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.github_com.mare11.xml_megatravel.user;
