version: '3'
services:

  exist:
    image: exist
    container_name: exist
    build:
      context: ./exist
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  discovery:
    image: discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image: gateway-service
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  accommodation-service:
    image: accommodation-service
    build:
     context: ./accommodation-service
     dockerfile: Dockerfile
    ports:
     - "8081:8081"
    depends_on:
     - discovery
     - exist
    links:
     - discovery:discovery
     - exist:exist
    
  authentication-service:
    image: authentication-service
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "2222"
    depends_on:
      - discovery
      - exist
    links:
      - discovery:discovery
      - exist:exist
  
  registration-service:
    image: registration-service
    build:
      context: ./registration-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery
      - exist
      - authentication-service
    links:
      - discovery:discovery
      - exist:exist
      - authentication-service:authentication-service
  
  reservation-service:
    image: reservation-service
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - discovery
      - exist
      - accommodation-service
      - user-service
    links:
      - discovery:discovery
      - exist:exist
      - accommodation-service:accommodation-service
      - user-service:user-service

  search-service:
    image: search-service
    build:
      context: ./search-service
      dockerfile: Dockerfile
    ports:
      - "2222"
    depends_on:
      - discovery
      - exist
      - reservation-service
    links:
      - discovery:discovery
      - exist:exist
      - reservation-service:reservation-service

  user-service:
    image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "2222"
    depends_on:
      - discovery
      - exist
    links:
      - discovery:discovery
      - exist:exist