//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.16 at 03:43:04 PM CEST 
//


package https.github_com.mare11.xml_megatravel.accommodation;

import java.time.LocalDate;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, LocalDate>
{


    public LocalDate unmarshal(String value) {
        return (org.xmlws.util.TypeConverter.parseDate(value));
    }

    public String marshal(LocalDate value) {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

}
